// wala-content-spa/src/components/ui/ToastNotification.jsx
import React from 'react';
import { useToastStore } from '../../store/toastStore';
import { CheckCircle2, AlertTriangle, Info, XCircle, X } from 'lucide-react';

const ICONS = {
  success: CheckCircle2,
  warning: AlertTriangle,
  info: Info,
  error: XCircle
};

const STYLES = {
  success: 'bg-emerald-950/90 border-emerald-500/30 text-emerald-100 shadow-emerald-950/20',
  warning: 'bg-amber-950/90 border-amber-500/30 text-amber-100 shadow-amber-950/20',
  info: 'bg-blue-950/90 border-blue-500/30 text-blue-100 shadow-blue-950/20',
  error: 'bg-rose-950/90 border-rose-500/30 text-rose-100 shadow-rose-950/20'
};

const ICON_COLORS = {
  success: 'text-emerald-400',
  warning: 'text-amber-400',
  info: 'text-blue-400',
  error: 'text-rose-400'
};

export default function ToastNotification() {
  const { toasts, removeToast } = useToastStore();

  if (toasts.length === 0) return null;

  return (
    <div className="fixed bottom-6 right-6 z-50 flex flex-col gap-3 max-w-sm w-full pointer-events-none">
      {toasts.map((toast) => {
        const Icon = ICONS[toast.type] || Info;
        const styleClass = STYLES[toast.type] || STYLES.info;
        const iconColor = ICON_COLORS[toast.type] || ICON_COLORS.info;

        return (
          <div
            key={toast.id}
            className={`flex items-center gap-3 p-4 rounded-xl border backdrop-blur-md shadow-2xl transition-all duration-300 animate-slide-in pointer-events-auto ${styleClass}`}
          >
            <div className={`flex-shrink-0 ${iconColor}`}>
              <Icon size={20} />
            </div>
            
            <div className="flex-1 text-xs font-semibold leading-relaxed">
              {toast.message}
            </div>

            <button
              onClick={() => removeToast(toast.id)}
              className="flex-shrink-0 p-1 rounded-lg hover:bg-white/10 text-slate-400 hover:text-white transition-colors"
            >
              <X size={14} />
            </button>
          </div>
        );
      })}
    </div>
  );
}

// src/components/ui/ToastNotification.vue
<template>
  <!-- Contenedor de múltiples toasts apilados -->
  <div
    class="fixed bottom-24 left-1/2 -translate-x-1/2 z-50 max-w-md w-full mx-auto px-4"
  >
    <transition-group
      name="toast"
      tag="div"
      class="flex flex-col-reverse gap-3"
    >
      <div
        v-for="toast in toasts"
        :key="toast.id"
        :class="[
          'rounded-xl shadow-lg border-2 p-4 flex items-center gap-3 toast-item',
          typeClasses[toast.type],
        ]"
      >
        <!-- Icon -->
        <div class="flex-shrink-0">
          <component
            :is="icons[toast.type]"
            :class="['w-6 h-6', iconColorClasses[toast.type]]"
          />
        </div>

        <!-- Message -->
        <p
          :class="['flex-1 text-sm font-medium', textColorClasses[toast.type]]"
        >
          {{ toast.message }}
        </p>

        <!-- Close Button -->
        <button
          v-if="toast.closable"
          @click="removeToast(toast.id)"
          :class="[
            'flex-shrink-0 p-1 rounded-lg transition-colors',
            closeButtonClasses[toast.type],
          ]"
        >
          <svg
            class="w-4 h-4"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M6 18L18 6M6 6l12 12"
            />
          </svg>
        </button>
      </div>
    </transition-group>
  </div>
</template>

<script setup>
import {
  InfoCircle,
  CheckCircle,
  WarningCircle,
  XmarkCircle,
  BrightCrown,
} from "@iconoir/vue";
import { useToast } from "@/composables/useToast";

const { toasts, removeToast } = useToast();

const icons = {
  info: InfoCircle,
  success: CheckCircle,
  warning: WarningCircle,
  error: XmarkCircle,
  premium: BrightCrown,
};

const typeClasses = {
  info: "bg-blue-50 border-blue-200",
  success: "bg-green-50 border-green-200",
  warning: "bg-amber-50 border-amber-200",
  error: "bg-red-50 border-red-200",
  premium: "bg-orange-50 border-orange-200",
};

const iconColorClasses = {
  info: "text-blue-600",
  success: "text-green-600",
  warning: "text-amber-600",
  error: "text-red-600",
  premium: "text-orange-600",
};

const textColorClasses = {
  info: "text-blue-900",
  success: "text-green-900",
  warning: "text-amber-900",
  error: "text-red-900",
  premium: "text-orange-900",
};

const closeButtonClasses = {
  info: "text-blue-600 hover:bg-blue-100",
  success: "text-green-600 hover:bg-green-100",
  warning: "text-amber-600 hover:bg-amber-100",
  error: "text-red-600 hover:bg-red-100",
  premium: "text-orange-600 hover:bg-orange-100",
};
</script>

<style scoped>
/* Animaciones de entrada y salida con fade out de 1 segundo */
.toast-enter-active {
  transition: all 0.3s ease-out;
}

.toast-leave-active {
  transition: all 1s ease-in;
}

.toast-enter-from {
  opacity: 0;
  transform: translateY(1rem) scale(0.95);
}

.toast-enter-to {
  opacity: 1;
  transform: translateY(0) scale(1);
}

.toast-leave-from {
  opacity: 1;
  transform: translateY(0) scale(1);
}

.toast-leave-to {
  opacity: 0;
  transform: translateY(1rem) scale(0.95);
}

/* Animación de movimiento cuando otros toasts se eliminan */
.toast-move {
  transition: transform 0.3s ease;
}
</style>
